### ISSUE TITLE
Option to choose how many tiles may be puchased

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-PurchaseIt#1]
Defaulting to 25, the option would allow user to specify number between 1 .. 25.

The limit applies when purchasing tiles; if they are at or above the limit they cannot purchase additional tiles.

Similar to this mod: [Extended Game Options](https://steamcommunity.com/sharedfiles/filedetails/?id=1237383751)

**Comment by keallu** [comment]
I've added this to my todo list but is has low priority.
